### ISSUE TITLE
Week of May 27, 2015

### ISSUE THREAD

**Issue by tcr** [tessel/this-week-in-tessel#3]
Goals for next week:
- Tessel 2 content / pictures 
- First-party tessel blog posts
- Contribution guidelines and options
- Hopefully a manufacturing update

**Comment by Frijol** [comment]
Since May 13:

Engineering
- New batch of boards came in https://twitter.com/technicalhumans/status/604004201975296000

Projects
- Tank robot with stepper motors by Sean Dutton https://twitter.com/seantdutton/status/598828578139152384
- Hackers at DragonHack built a Myo-controlled robot car https://twitter.com/MLHacks/status/599930571154939904
- Steve Caldwell hacked a Tonka truck with his son https://twitter.com/stevecaldwell/status/599632433135386624
- Yodazone by Anubhooti Pareek helps relieve stress https://www.youtube.com/watch?v=0tFhtU6F1bk
- No Stair Runner, by Ella https://www.youtube.com/watch?v=CBFUclx7NlU
- A car that runs from light https://www.youtube.com/watch?v=zKIr_A3dpGE&feature=youtu.be&a
- Zac Colley made a new community module! Now you can use a thermal printer from Tessel: https://github.com/zaccolley/tessel-thermalprinter
- I'm not sure, I think this is a hello world? Does anyone speak Japanese? https://twitter.com/milkotn/status/605329071602466817

Blogs
- Sending RFID Events in Realtime by PubNub http://www.pubnub.com/blog/sending-rfid-events-in-realtime-w-tessel-rfid-module/
- Acting on RFID Events in Realtime (part 2) by PubNub http://www.pubnub.com/blog/acting-on-tessel-rfid-events-with-tessel-rfid-module/
- Tessel 2: placa de desarrollo para el IoT http://www.linuxadictos.com/tessel-2-placa-de-desarrollo-para-el-iot.html
- Tessel Camera module + Project Oxford Face APIs http://hypernephelist.com/2015/05/18/tessel-camera-project-oxford-face-api.html
- Offenes Entwicklerboard soll wie Io.js verwaltet werden http://www.golem.de/news/tessel-offenes-entwicklerboard-soll-wie-io-js-verwaltet-werden-1505-114218.html
- Remote Control and Monitoring for Tessel Servo by PubNub http://www.pubnub.com/blog/remote-control-and-monitoring-for-tessel-servo/
- The Time I Took my 6 Year Old to a Hackathon by Tim Lytle http://www.programmableweb.com/news/time-i-took-my-6-year-old-to-hackathon/analysis/2015/05/21

Tessel around the world
- Julian Cheal presented about JS Hardware Hacking at JS Conf Budapest https://twitter.com/slsoftworks/status/598870106567999488
- SAP held a Tessel CodeJam in the Netherlands https://twitter.com/Sygyzmundovych/status/604295000491446272
- Microsoft Azure held an IoT hackathon in Stockholm https://twitter.com/bjorn_eriksen/status/603862010300919808
- Tessel was at WearHacks Paris, a wearables + IoT hackathon https://twitter.com/BenoitDat/status/602494338581528576
- IoT Projects Showcase at Xoriant in Sunnyvale http://rominirani.com/2015/06/02/iot-projects-showcase/
- Wouter Verweirder presented Node on hardware at Hookedfest in Belgium https://twitter.com/wouter/status/605673683663880192

**Comment by johnnyman727** [comment]
This is really cool too: https://github.com/andrewcashmore/node-lego-ir

**Comment by Frijol** [comment]
There's also this nice setup video https://www.youtube.com/watch?v=WOtHm11PepQ

**Comment by tcr3dr** [comment]
Collab here: https://docs.google.com/document/d/1qRBhy3QUScNtwDRTUNvVzjS_O4_MbWl1YCgkbCsjOXM/edit?usp=sharing

**Comment by tcr** [comment]
Collab here: https://docs.google.com/document/d/1qRBhy3QUScNtwDRTUNvVzjS_O4_MbWl1YCgkbCsjOXM/edit?usp=sharing
